name: Publish GitHub Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use checkout@v3 action
        uses: actions/checkout@v3
      - name: Use setup-node@v3 action
        uses: actions/setup-node@v3
      - name: With Node v16
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Build source code
        run: npm run build
      - name: Unit test
        run: npm test

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Use checkout@v3 actions
        uses: actions/checkout@v3
      - name: Use setup-node@v3 action
        uses: actions/setup-node@v3
      - name: With Node v16
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org//
      - name: Install dependencies
        run: npm ci
      - name: Build source code
        run: npm run build
      - name: Set registry
        run: npm config set registry https://registry.npmjs.org/
      - name: Set authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish package
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
